name: Selective Build and Test in Package Dirs

on:
  push:
    branches: [main]
    paths:
      - "packages/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
  pull_request:
    paths:
      - "packages/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"

jobs:
  build-test-changed-in-dirs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
        id: pnpmcache
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpmcache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Determine Base Ref
        id: vars
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "base_ref=origin/${{ github.base_ref }}" >> $GITHUB_OUTPUT
          else
            # Push의 경우, main 브랜치와 비교 (필요시 수정)
            echo "base_ref=origin/main" >> $GITHUB_OUTPUT
          fi
          echo "Calculated base ref: ${{ steps.vars.outputs.base_ref }}"

      - name: Install Root Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Changed Packages & Dependents (in their dirs)
        run: |
          echo "Running build script within packages changed since ${{ steps.vars.outputs.base_ref }}"
          pnpm -r --filter "...[${{ steps.vars.outputs.base_ref }}]" \
                  --filter=!./packages/api \
                  --filter=!./packages/backend \
                  run --if-present build

      - name: Test Changed Packages & Dependents (in their dirs)
        run: |
          echo "Running test script within packages changed since ${{ steps.vars.outputs.base_ref }}"
          pnpm -r --filter "...[${{ steps.vars.outputs.base_ref }}]" \
                  --filter=!./packages/api \
                  --filter=!./packages/backend \
                  run --if-present test
