name: build and publish dry run
on:
  push:
  pull_request:

jobs:
  determine-changed-packages:
    runs-on: ubuntu-latest
    needs: check-list-updated
    outputs:
      changed_packages: ${{ steps.list-packages.outputs.packages }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Get pnpm store directory
        id: pnpmcache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpmcache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Determine Base Ref
        id: vars
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "base_ref=origin/${{ github.base_ref }}" >> $GITHUB_OUTPUT
          else
            echo "base_ref=origin/main^" >> $GITHUB_OUTPUT
          fi
          echo "Determined base ref: $(cat $GITHUB_OUTPUT | grep base_ref)"

      - name: Install Root Dependencies (for pnpm ls)
        run: pnpm install --frozen-lockfile

      - name: List Changed Packages (incl. dependents, excl. specific ones)
        id: list-packages
        run: |
          if ! command -v jq &> /dev/null; then
            sudo apt-get update && sudo apt-get install -y jq
          fi
          echo "Base ref for diff: ${{ steps.vars.outputs.base_ref }}"
          CHANGED_PACKAGES_JSON=$(pnpm ls -r --depth -1 --json \
            --filter "...[${{ steps.vars.outputs.base_ref }}]" \
            --filter=!./packages/api \
            --filter=!./packages/backend \
            --filter=!@wrtn/connector \
            | jq -c '[.[] | {full_name: .name, short_name: (.path | split("/")[-1])}]')
          echo "Raw changed packages JSON (objects): $CHANGED_PACKAGES_JSON"
          echo "packages=${CHANGED_PACKAGES_JSON}" >> $GITHUB_OUTPUT

  build-and-publish-dry-run:
    runs-on: ubuntu-latest
    needs: determine-changed-packages
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: 10

      - run: pnpm install --frozen-lockfile

      - name: Dry Run Publish Changed Packages
        env:
          CHANGED_PACKAGES: ${{ needs.determine-changed-packages.outputs.changed_packages }}
        run: |
          echo "Changed packages: $CHANGED_PACKAGES"
          PACKAGE_PATHS=$(echo "$CHANGED_PACKAGES" | jq -r '.[].short_name' | xargs -I{} echo "./packages/{}")
          echo "Filtered package paths: $PACKAGE_PATHS"

          if [ -z "$PACKAGE_PATHS" ]; then
            echo "No packages to publish. Skipping dry run."
            exit 0
          fi

          pnpm dlx pkg-pr-new publish --pnpm $PACKAGE_PATHS
