name: Selective Build and Test in Package Dirs

on:
  push:
    branches: [ main ]
    paths:
      - "packages/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
  pull_request:
    paths:
      - "packages/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - ".github/workflows/build.yml"

jobs:
  build-test-changed-in-dirs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 변경사항 비교 위해 전체 Git 히스토리 필요

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      # pnpm 캐시 설정 (이전과 동일)
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
        id: pnpmcache
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpmcache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Determine Base Ref
        id: vars
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "base_ref=origin/${{ github.base_ref }}" >> $GITHUB_OUTPUT
          else
            # Push의 경우, main 브랜치와 비교 (필요시 수정)
            echo "base_ref=origin/main" >> $GITHUB_OUTPUT
          fi
          echo "Calculated base ref: ${{ steps.vars.outputs.base_ref }}"

      - name: Install Root Dependencies
        run: pnpm install --frozen-lockfile # 루트 의존성 및 워크스페이스 링크 설치

      # 변경된 패키지 + 의존성 있는 패키지 내부에서 'build' 스크립트 실행
      # -r 옵션: 필터링된 각 패키지에서 명령 실행
      # run build: 각 패키지의 package.json에 있는 'build' 스크립트 실행
      # --if-present: 해당 스크립트가 없을 경우 에러 없이 건너뜀
      - name: Build Changed Packages & Dependents (in their dirs)
        run: |
          echo "Running build script within packages changed since ${{ steps.vars.outputs.base_ref }}"
          pnpm -r --filter "...[${{ steps.vars.outputs.base_ref }}]" \
                  --filter=!./packages/api \
                  --filter=!./packages/backend \
                  run --if-present build

      # 변경된 패키지 + 의존성 있는 패키지 내부에서 'test' 스크립트 실행
      - name: Test Changed Packages & Dependents (in their dirs)
        run: |
          echo "Running test script within packages changed since ${{ steps.vars.outputs.base_ref }}"
          pnpm -r --filter "...[${{ steps.vars.outputs.base_ref }}]" \
                  --filter=!./packages/api \
                  --filter=!./packages/backend \
                  run --if-present test