# author: elliot-huffman
name: release
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: none
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - name: Publish to NPM
        run: pnpm package:latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
