name: Version Bump

on:
  push:
    branches:
      - main
    paths:
      - "src/api/structures/**"
      - "src/controllers/**"
      - "src/executable/**"
      - "package.json"

jobs:
  version_bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Secrets to Env
        run: |
          rm .env
          jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' <<< "$SECRETS_CONTEXT" > .env
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: Root Install
        run: pnpm install && pnpm build:prisma

      - name: Build
        working-directory: website
        run: pnpm install && pnpm build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8 # v4.7.3
        with:
          branch: gh-pages
          folder: ./website/out

      - name: Checkout repository for versioning
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          branch: main

      - name: Bump version for swagger
        run: |
          git config --local user.email "studio@wrtn.io"
          git config --local user.name "studio-pro"
          git pull
          npm version patch -m "Bump swagger version to %s [skip ci]"
          git push --set-upstream origin main --follow-tags

      - name: Bump version for sdk
        working-directory: packages/api
        run: |
          git config --local user.email "studio@wrtn.io"
          git config --local user.name "studio-pro"
          git pull
          npm version patch
          git add *
          git commit --no-verify -m "Bump sdk version to %s [skip ci]"
          git push --set-upstream origin main
        #   npm run deploy
        # env:
        #   NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
